import {
  DEFAULT_NOTIFICATION_PREFERENCES,
  type ProfileNotificationPreferences,
} from '@/types/profile';
import {
  NOTIFICATION_CATEGORIES,
  type NotificationCategory,
  type NotificationDeliveryKind,
  type NotificationScheduleBuildInput,
  type NotificationScheduleBuildResult,
  type NotificationScheduleItem,
  type NotificationScheduleMetadata,
  type NotificationScheduleStatus,
  type NotificationSource,
} from '@/types/notification';
import {
  buildHebcalNotificationCandidate,
  isHebcalNotificationCategory,
} from '@/services/notificationHebcalPlannerService';
import { buildBirthdayNotificationCandidates } from '@/services/notificationBirthdayPlannerService';
import { buildEventNotificationCandidates } from '@/services/notificationEventPlannerService';

type CategoryScheduleDefinition = {
  body: string;
  deliveryKind: NotificationDeliveryKind;
  disabledReason: string;
  metadata?: NotificationScheduleMetadata;
  source: NotificationSource;
  title: string;
  unsupportedReason: string;
};

const CATEGORY_SCHEDULE_DEFINITIONS: Record<NotificationCategory, CategoryScheduleDefinition> = {
  prayers: {
    body: 'Prayer reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The prayers notification preference is disabled.',
    source: 'hebcal',
    title: 'Prayers',
    unsupportedReason: 'Prayer reminder planning is not implemented in this PR.',
  },
  shabbat: {
    body: 'Shabbat reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The Shabbat notification preference is disabled.',
    source: 'hebcal',
    title: 'Shabbat',
    unsupportedReason: 'Shabbat reminder planning is not implemented in this PR.',
  },
  holidays: {
    body: 'Holiday reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The holidays notification preference is disabled.',
    source: 'hebcal',
    title: 'Holidays',
    unsupportedReason: 'Holiday reminder planning is not implemented in this PR.',
  },
  candles: {
    body: 'Candle lighting reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The candle lighting notification preference is disabled.',
    source: 'hebcal',
    title: 'Candle lighting',
    unsupportedReason: 'Candle lighting reminder planning is not implemented in this PR.',
  },
  events: {
    body: 'Event reminder preview will be generated from visible events and registrations later.',
    deliveryKind: 'local',
    disabledReason: 'The events notification preference is disabled.',
    metadata: {
      plannedDeliveryKinds: ['local', 'remote_future'],
      plannedSources: ['events', 'registrations'],
    },
    source: 'events',
    title: 'Events',
    unsupportedReason: 'Event reminder planning is not implemented in this PR.',
  },
  birthdays: {
    body: 'Birthday reminder preview uses already visible community contacts and already loaded local iPhone contacts.',
    deliveryKind: 'local',
    disabledReason: 'The birthdays notification preference is disabled.',
    metadata: {
      plannedSources: ['community_contacts', 'iphone_contacts'],
    },
    source: 'unknown',
    title: 'Birthdays',
    unsupportedReason: 'Birthday reminder planning requires visible community contacts or loaded local iPhone contacts.',
  },
  weekly: {
    body: 'Weekly Jewish content preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The weekly notification preference is disabled.',
    source: 'hebcal',
    title: 'Weekly',
    unsupportedReason: 'Weekly reminder planning is not implemented in this PR.',
  },
  news: {
    body: 'News delivery remains a future remote push scenario.',
    deliveryKind: 'remote_future',
    disabledReason: 'The news notification preference is disabled.',
    source: 'manual',
    title: 'News',
    unsupportedReason: 'News push delivery is not implemented in this PR.',
  },
};

type NumericNotificationPreferenceKey = Extract<
  keyof ProfileNotificationPreferences,
  | 'candlesReminderOffsetMinutes'
  | 'shabbatReminderOffsetHours'
  | 'holidaysReminderHour'
  | 'weeklyReminderOffsetHours'
  | 'birthdaysReminderHour'
  | 'eventsPrimaryReminderOffsetHours'
  | 'eventsFallbackReminderOffsetHours'
>;

type NumericNotificationPreferenceRange = {
  defaultValue: number;
  max: number;
  min: number;
};

const NUMERIC_NOTIFICATION_PREFERENCE_RANGES: Record<
  NumericNotificationPreferenceKey,
  NumericNotificationPreferenceRange
> = {
  birthdaysReminderHour: { defaultValue: 9, max: 18, min: 6 },
  candlesReminderOffsetMinutes: { defaultValue: 60, max: 180, min: 15 },
  eventsFallbackReminderOffsetHours: { defaultValue: 2, max: 12, min: 1 },
  eventsPrimaryReminderOffsetHours: { defaultValue: 24, max: 72, min: 2 },
  holidaysReminderHour: { defaultValue: 9, max: 18, min: 6 },
  shabbatReminderOffsetHours: { defaultValue: 8, max: 24, min: 2 },
  weeklyReminderOffsetHours: { defaultValue: 8, max: 24, min: 2 },
};

const QUIET_HOURS_TIME_PATTERN = /^([01]\d|2[0-3]):([0-5]\d)$/;
const DAY_MINUTES = 24 * 60;

function normalizeNumericNotificationPreference(
  value: unknown,
  range: NumericNotificationPreferenceRange,
): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return range.defaultValue;
  }

  return Math.min(range.max, Math.max(range.min, Math.round(value)));
}

function normalizeQuietHoursTime(value: unknown, fallback: string): string {
  if (typeof value === 'string' && QUIET_HOURS_TIME_PATTERN.test(value)) {
    return value;
  }

  return fallback;
}

function parseTimeToMinutes(value: string): number {
  const [hours, minutes] = value.split(':').map(Number);
  return hours * 60 + minutes;
}

function getDateMinutesInTimezone(date: Date, timezone: string | null | undefined): number | null {
  const options: Intl.DateTimeFormatOptions = {
    hour: '2-digit',
    hour12: false,
    minute: '2-digit',
  };

  if (timezone) {
    options.timeZone = timezone;
  }

  try {
    const formattedTime = new Intl.DateTimeFormat('en-GB', options).format(date);
    const match = formattedTime.match(/^(\d{2}):(\d{2})$/);

    if (!match) {
      return null;
    }

    const hours = Number(match[1]);
    const minutes = Number(match[2]);

    if (!Number.isFinite(hours) || !Number.isFinite(minutes)) {
      return null;
    }

    return ((hours * 60 + minutes) % DAY_MINUTES + DAY_MINUTES) % DAY_MINUTES;
  } catch {
    return null;
  }
}

function isDateInsideQuietHours(
  date: Date,
  preferences: ProfileNotificationPreferences,
  timezone: string | null | undefined,
): boolean {
  if (!preferences.quietHoursEnabled) {
    return false;
  }

  const currentMinutes = getDateMinutesInTimezone(date, timezone);

  if (currentMinutes === null) {
    return false;
  }

  const startMinutes = parseTimeToMinutes(preferences.quietHoursStart ?? '22:00');
  const endMinutes = parseTimeToMinutes(preferences.quietHoursEnd ?? '08:00');

  if (startMinutes === endMinutes) {
    return false;
  }

  if (startMinutes < endMinutes) {
    return currentMinutes >= startMinutes && currentMinutes < endMinutes;
  }

  return currentMinutes >= startMinutes || currentMinutes < endMinutes;
}

function addQuietHoursMetadata(
  item: NotificationScheduleItem,
  input: NotificationScheduleBuildInput,
  preferences: ProfileNotificationPreferences,
): NotificationScheduleItem {
  const triggerAt = item.triggerAt ? new Date(item.triggerAt) : null;
  const timezone = item.timezone ?? input.timezone ?? null;
  const isInsideQuietHours = item.status === 'candidate'
    && triggerAt instanceof Date
    && Number.isFinite(triggerAt.getTime())
    && isDateInsideQuietHours(triggerAt, preferences, timezone);

  return {
    ...item,
    metadata: {
      ...item.metadata,
      isInsideQuietHours,
      quietHoursEnabled: preferences.quietHoursEnabled === true,
    },
  };
}

export function normalizeNotificationPreferencesForSchedule(
  preferences: ProfileNotificationPreferences | null | undefined,
): ProfileNotificationPreferences {
  const source: Partial<ProfileNotificationPreferences> = preferences ?? {};

  return {
    ...DEFAULT_NOTIFICATION_PREFERENCES,
    ...source,
    prayers: typeof source.prayers === 'boolean' ? source.prayers : DEFAULT_NOTIFICATION_PREFERENCES.prayers,
    shabbat: typeof source.shabbat === 'boolean' ? source.shabbat : DEFAULT_NOTIFICATION_PREFERENCES.shabbat,
    holidays: typeof source.holidays === 'boolean' ? source.holidays : DEFAULT_NOTIFICATION_PREFERENCES.holidays,
    candles: typeof source.candles === 'boolean' ? source.candles : DEFAULT_NOTIFICATION_PREFERENCES.candles,
    events: typeof source.events === 'boolean' ? source.events : DEFAULT_NOTIFICATION_PREFERENCES.events,
    birthdays: typeof source.birthdays === 'boolean' ? source.birthdays : DEFAULT_NOTIFICATION_PREFERENCES.birthdays,
    weekly: typeof source.weekly === 'boolean' ? source.weekly : DEFAULT_NOTIFICATION_PREFERENCES.weekly,
    news: typeof source.news === 'boolean' ? source.news : DEFAULT_NOTIFICATION_PREFERENCES.news,
    candlesReminderOffsetMinutes: normalizeNumericNotificationPreference(
      source.candlesReminderOffsetMinutes,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.candlesReminderOffsetMinutes,
    ),
    shabbatReminderOffsetHours: normalizeNumericNotificationPreference(
      source.shabbatReminderOffsetHours,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.shabbatReminderOffsetHours,
    ),
    holidaysReminderHour: normalizeNumericNotificationPreference(
      source.holidaysReminderHour,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.holidaysReminderHour,
    ),
    weeklyReminderOffsetHours: normalizeNumericNotificationPreference(
      source.weeklyReminderOffsetHours,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.weeklyReminderOffsetHours,
    ),
    birthdaysReminderHour: normalizeNumericNotificationPreference(
      source.birthdaysReminderHour,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.birthdaysReminderHour,
    ),
    eventsPrimaryReminderOffsetHours: normalizeNumericNotificationPreference(
      source.eventsPrimaryReminderOffsetHours,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.eventsPrimaryReminderOffsetHours,
    ),
    eventsFallbackReminderOffsetHours: normalizeNumericNotificationPreference(
      source.eventsFallbackReminderOffsetHours,
      NUMERIC_NOTIFICATION_PREFERENCE_RANGES.eventsFallbackReminderOffsetHours,
    ),
    quietHoursEnabled: typeof source.quietHoursEnabled === 'boolean'
      ? source.quietHoursEnabled
      : DEFAULT_NOTIFICATION_PREFERENCES.quietHoursEnabled ?? false,
    quietHoursStart: normalizeQuietHoursTime(
      source.quietHoursStart,
      DEFAULT_NOTIFICATION_PREFERENCES.quietHoursStart ?? '22:00',
    ),
    quietHoursEnd: normalizeQuietHoursTime(
      source.quietHoursEnd,
      DEFAULT_NOTIFICATION_PREFERENCES.quietHoursEnd ?? '08:00',
    ),
  };
}

function createBaseScheduleItem(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
  status: NotificationScheduleStatus,
  reason: string,
): NotificationScheduleItem {
  const definition = CATEGORY_SCHEDULE_DEFINITIONS[category];

  return {
    id: `notification-schedule-preview:${category}:${status}`,
    body: definition.body,
    category,
    deliveryKind: definition.deliveryKind,
    metadata: definition.metadata,
    reason,
    relatedEntityId: null,
    relatedEntityType: null,
    source: definition.source,
    status,
    timezone: input.timezone ?? null,
    title: definition.title,
    triggerAt: null,
  };
}

export function createUnsupportedScheduleItem(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
  reason = CATEGORY_SCHEDULE_DEFINITIONS[category].unsupportedReason,
): NotificationScheduleItem {
  return createBaseScheduleItem(category, input, 'unsupported_in_this_pr', reason);
}

export function createDisabledScheduleItem(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
  reason = CATEGORY_SCHEDULE_DEFINITIONS[category].disabledReason,
): NotificationScheduleItem {
  return createBaseScheduleItem(category, input, 'disabled_by_preferences', reason);
}

export function buildCategorySchedulePreview(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
): NotificationScheduleItem {
  return buildCategorySchedulePreviewItems(category, input)[0];
}

function buildCategorySchedulePreviewItems(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
): NotificationScheduleItem[] {
  const preferences = normalizeNotificationPreferencesForSchedule(input.preferences);
  const normalizedInput: NotificationScheduleBuildInput = {
    ...input,
    preferences,
  };
  let items: NotificationScheduleItem[];

  if (!preferences[category]) {
    items = [createDisabledScheduleItem(category, normalizedInput)];
  } else if (isHebcalNotificationCategory(category)) {
    items = [buildHebcalNotificationCandidate(category, normalizedInput)];
  } else if (category === 'birthdays') {
    items = buildBirthdayNotificationCandidates(normalizedInput);
  } else if (category === 'events') {
    items = buildEventNotificationCandidates(normalizedInput);
  } else {
    items = [createUnsupportedScheduleItem(category, normalizedInput)];
  }

  return items.map((item) => addQuietHoursMetadata(item, normalizedInput, preferences));
}

function countItemsByStatus(
  items: readonly NotificationScheduleItem[],
  status: NotificationScheduleStatus,
): number {
  return items.filter((item) => item.status === status).length;
}

export function buildNotificationSchedulePreview(
  input: NotificationScheduleBuildInput,
): NotificationScheduleBuildResult {
  const preferences = normalizeNotificationPreferencesForSchedule(input.preferences);
  const normalizedInput: NotificationScheduleBuildInput = {
    ...input,
    preferences,
  };
  const items = NOTIFICATION_CATEGORIES.flatMap((category) => buildCategorySchedulePreviewItems(category, normalizedInput));
  const enabledCategoryCount = NOTIFICATION_CATEGORIES.filter((category) => preferences[category]).length;

  return {
    candidateCount: countItemsByStatus(items, 'candidate'),
    disabledCategoryCount: countItemsByStatus(items, 'disabled_by_preferences'),
    enabledCategoryCount,
    items,
    needsDataCount: countItemsByStatus(items, 'needs_data'),
    skippedCount: countItemsByStatus(items, 'skipped'),
    unsupportedCount: countItemsByStatus(items, 'unsupported_in_this_pr'),
  };
}
