import {
  DEFAULT_NOTIFICATION_PREFERENCES,
  type ProfileNotificationPreferences,
} from '@/types/profile';
import {
  NOTIFICATION_CATEGORIES,
  type NotificationCategory,
  type NotificationDeliveryKind,
  type NotificationScheduleBuildInput,
  type NotificationScheduleBuildResult,
  type NotificationScheduleItem,
  type NotificationScheduleMetadata,
  type NotificationScheduleStatus,
  type NotificationSource,
} from '@/types/notification';
import {
  buildHebcalNotificationCandidate,
  isHebcalNotificationCategory,
} from '@/services/notificationHebcalPlannerService';
import { buildBirthdayNotificationCandidates } from '@/services/notificationBirthdayPlannerService';

type CategoryScheduleDefinition = {
  body: string;
  deliveryKind: NotificationDeliveryKind;
  disabledReason: string;
  metadata?: NotificationScheduleMetadata;
  source: NotificationSource;
  title: string;
  unsupportedReason: string;
};

const CATEGORY_SCHEDULE_DEFINITIONS: Record<NotificationCategory, CategoryScheduleDefinition> = {
  prayers: {
    body: 'Prayer reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The prayers notification preference is disabled.',
    source: 'hebcal',
    title: 'Prayers',
    unsupportedReason: 'Prayer reminder planning is not implemented in this PR.',
  },
  shabbat: {
    body: 'Shabbat reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The Shabbat notification preference is disabled.',
    source: 'hebcal',
    title: 'Shabbat',
    unsupportedReason: 'Shabbat reminder planning is not implemented in this PR.',
  },
  holidays: {
    body: 'Holiday reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The holidays notification preference is disabled.',
    source: 'hebcal',
    title: 'Holidays',
    unsupportedReason: 'Holiday reminder planning is not implemented in this PR.',
  },
  candles: {
    body: 'Candle lighting reminder preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The candle lighting notification preference is disabled.',
    source: 'hebcal',
    title: 'Candle lighting',
    unsupportedReason: 'Candle lighting reminder planning is not implemented in this PR.',
  },
  events: {
    body: 'Event reminder preview will be generated from visible events and registrations later.',
    deliveryKind: 'local',
    disabledReason: 'The events notification preference is disabled.',
    metadata: {
      plannedDeliveryKinds: ['local', 'remote_future'],
      plannedSources: ['events', 'registrations'],
    },
    source: 'events',
    title: 'Events',
    unsupportedReason: 'Event reminder planning is not implemented in this PR.',
  },
  birthdays: {
    body: 'Birthday reminder preview uses already visible community contacts and already loaded local iPhone contacts.',
    deliveryKind: 'local',
    disabledReason: 'The birthdays notification preference is disabled.',
    metadata: {
      plannedSources: ['community_contacts', 'iphone_contacts'],
    },
    source: 'unknown',
    title: 'Birthdays',
    unsupportedReason: 'Birthday reminder planning requires visible community contacts or loaded local iPhone contacts.',
  },
  weekly: {
    body: 'Weekly Jewish content preview will be generated by the Hebcal reminder PR.',
    deliveryKind: 'local',
    disabledReason: 'The weekly notification preference is disabled.',
    source: 'hebcal',
    title: 'Weekly',
    unsupportedReason: 'Weekly reminder planning is not implemented in this PR.',
  },
  news: {
    body: 'News delivery remains a future remote push scenario.',
    deliveryKind: 'remote_future',
    disabledReason: 'The news notification preference is disabled.',
    source: 'manual',
    title: 'News',
    unsupportedReason: 'News push delivery is not implemented in this PR.',
  },
};

export function normalizeNotificationPreferencesForSchedule(
  preferences: ProfileNotificationPreferences | null | undefined,
): ProfileNotificationPreferences {
  const source: Partial<ProfileNotificationPreferences> = preferences ?? {};

  return {
    ...DEFAULT_NOTIFICATION_PREFERENCES,
    ...source,
    prayers: typeof source.prayers === 'boolean' ? source.prayers : DEFAULT_NOTIFICATION_PREFERENCES.prayers,
    shabbat: typeof source.shabbat === 'boolean' ? source.shabbat : DEFAULT_NOTIFICATION_PREFERENCES.shabbat,
    holidays: typeof source.holidays === 'boolean' ? source.holidays : DEFAULT_NOTIFICATION_PREFERENCES.holidays,
    candles: typeof source.candles === 'boolean' ? source.candles : DEFAULT_NOTIFICATION_PREFERENCES.candles,
    events: typeof source.events === 'boolean' ? source.events : DEFAULT_NOTIFICATION_PREFERENCES.events,
    birthdays: typeof source.birthdays === 'boolean' ? source.birthdays : DEFAULT_NOTIFICATION_PREFERENCES.birthdays,
    weekly: typeof source.weekly === 'boolean' ? source.weekly : DEFAULT_NOTIFICATION_PREFERENCES.weekly,
    news: typeof source.news === 'boolean' ? source.news : DEFAULT_NOTIFICATION_PREFERENCES.news,
  };
}

function createBaseScheduleItem(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
  status: NotificationScheduleStatus,
  reason: string,
): NotificationScheduleItem {
  const definition = CATEGORY_SCHEDULE_DEFINITIONS[category];

  return {
    id: `notification-schedule-preview:${category}:${status}`,
    body: definition.body,
    category,
    deliveryKind: definition.deliveryKind,
    metadata: definition.metadata,
    reason,
    relatedEntityId: null,
    relatedEntityType: null,
    source: definition.source,
    status,
    timezone: input.timezone ?? null,
    title: definition.title,
    triggerAt: null,
  };
}

export function createUnsupportedScheduleItem(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
  reason = CATEGORY_SCHEDULE_DEFINITIONS[category].unsupportedReason,
): NotificationScheduleItem {
  return createBaseScheduleItem(category, input, 'unsupported_in_this_pr', reason);
}

export function createDisabledScheduleItem(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
  reason = CATEGORY_SCHEDULE_DEFINITIONS[category].disabledReason,
): NotificationScheduleItem {
  return createBaseScheduleItem(category, input, 'disabled_by_preferences', reason);
}

export function buildCategorySchedulePreview(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
): NotificationScheduleItem {
  return buildCategorySchedulePreviewItems(category, input)[0];
}

function buildCategorySchedulePreviewItems(
  category: NotificationCategory,
  input: NotificationScheduleBuildInput,
): NotificationScheduleItem[] {
  const preferences = normalizeNotificationPreferencesForSchedule(input.preferences);

  if (!preferences[category]) {
    return [createDisabledScheduleItem(category, input)];
  }

  if (isHebcalNotificationCategory(category)) {
    return [buildHebcalNotificationCandidate(category, input)];
  }

  if (category === 'birthdays') {
    return buildBirthdayNotificationCandidates(input);
  }

  return [createUnsupportedScheduleItem(category, input)];
}

function countItemsByStatus(
  items: readonly NotificationScheduleItem[],
  status: NotificationScheduleStatus,
): number {
  return items.filter((item) => item.status === status).length;
}

export function buildNotificationSchedulePreview(
  input: NotificationScheduleBuildInput,
): NotificationScheduleBuildResult {
  const preferences = normalizeNotificationPreferencesForSchedule(input.preferences);
  const normalizedInput: NotificationScheduleBuildInput = {
    ...input,
    preferences,
  };
  const items = NOTIFICATION_CATEGORIES.flatMap((category) => buildCategorySchedulePreviewItems(category, normalizedInput));
  const enabledCategoryCount = NOTIFICATION_CATEGORIES.filter((category) => preferences[category]).length;

  return {
    candidateCount: countItemsByStatus(items, 'candidate'),
    disabledCategoryCount: countItemsByStatus(items, 'disabled_by_preferences'),
    enabledCategoryCount,
    items,
    needsDataCount: countItemsByStatus(items, 'needs_data'),
    skippedCount: countItemsByStatus(items, 'skipped'),
    unsupportedCount: countItemsByStatus(items, 'unsupported_in_this_pr'),
  };
}
