import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import type { SeatingGuestPoolItem, SeatingReservePoolItem } from "../../types/seating";
import { formatPaymentStatus, getRegistrationStatusLabel } from "../registrations/formatters";

export type DialogTriggerRect = { left: number; top: number; width: number; height: number };
type Filter = "all" | "seated" | "unseated";
type Party = { id: string; guests: SeatingGuestPoolItem[]; name: string; options: string[]; status: string | null; payment: string | null };

export function SeatingUnseatedDialog({ fullListGuests, onClose, onGuestSelect, placementByGuestKey, reserves, triggerRect }: { fullListGuests: SeatingGuestPoolItem[]; onClose: () => void; onGuestSelect: (key: string) => boolean; placementByGuestKey: Map<string, string>; reserves: SeatingReservePoolItem[]; triggerRect: DialogTriggerRect | null }) {
  const dialogRef = useRef<HTMLDivElement | null>(null); const closeRef = useRef<HTMLButtonElement | null>(null); const timeout = useRef<number | null>(null);
  const [open, setOpen] = useState(false); const [closing, setClosing] = useState(false); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [origin, setOrigin] = useState<string>();
  const seated = fullListGuests.filter((guest) => placementByGuestKey.has(guest.key)).length; const needle = query.trim().toLocaleLowerCase("ru-RU");
  const guests = useMemo(() => fullListGuests.filter((guest) => { const placed = placementByGuestKey.has(guest.key); if (filter === "seated" && !placed) return false; if (filter === "unseated" && placed) return false; return !needle || [displayName(guest, guest.participantDisplayName || ""), guest.sourceLabel, ...guest.optionTitles, guest.status ? getRegistrationStatusLabel(guest.status) : "", guest.paymentStatus ? formatPaymentStatus(guest.paymentStatus) : "", placementByGuestKey.get(guest.key) ?? "Не рассажен"].join(" ").toLocaleLowerCase("ru-RU").includes(needle); }), [filter, fullListGuests, needle, placementByGuestKey]);
  const parties = useMemo(() => group(guests), [guests]);
  const requestClose = () => { if (closing) return; setClosing(true); if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) { onClose(); return; } setOpen(false); timeout.current = window.setTimeout(onClose, 240); };
  useEffect(() => { const frame = requestAnimationFrame(() => setOpen(true)); return () => { cancelAnimationFrame(frame); if (timeout.current) clearTimeout(timeout.current); }; }, []);
  useLayoutEffect(() => { if (!triggerRect || !dialogRef.current) return; const rect = dialogRef.current.getBoundingClientRect(); setOrigin(`${triggerRect.left + triggerRect.width / 2 - rect.left}px ${triggerRect.top + triggerRect.height / 2 - rect.top}px`); }, [triggerRect]);
  useEffect(() => { const before = document.activeElement; closeRef.current?.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); requestClose(); return; } if (event.key !== "Tab" || !dialogRef.current) return; const all = Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])')); if (!all.length) return; const first = all[0], last = all[all.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", keydown, true); return () => { document.removeEventListener("keydown", keydown, true); if (before instanceof HTMLElement) before.focus(); }; }, []);
  if (typeof document === "undefined") return null;
  return createPortal(<div className={["seat-unseated-dialog-overlay", open ? "is-open" : ""].filter(Boolean).join(" ")} onMouseDown={(event) => { if (event.target === event.currentTarget) requestClose(); }}><div aria-describedby="seat-unseated-dialog-count" aria-labelledby="seat-unseated-dialog-title" aria-modal="true" className="seat-unseated-dialog" ref={dialogRef} role="dialog" style={{ transformOrigin: origin }} tabIndex={-1}>
    <header className="seat-unseated-dialog__head"><div><span>Гости</span><h3 id="seat-unseated-dialog-title">Весь список</h3><p id="seat-unseated-dialog-count">Всего: {person(fullListGuests.length)} · {registrations(new Set(fullListGuests.map((guest) => guest.registrationId)).size)}</p></div><button aria-label="Закрыть полный список гостей" className="seat-unseated-dialog__close" onClick={requestClose} ref={closeRef} type="button">×</button></header>
    <div className="seat-unseated-dialog__tools"><label className="seat-unseated-dialog__search"><SearchIcon /><input aria-label="Поиск по списку гостей" onChange={(event) => setQuery(event.target.value)} placeholder="Имя, трапеза, стол" type="search" value={query} /></label>{([ ["all", "Все", fullListGuests.length], ["seated", "Рассажены", seated], ["unseated", "Не рассажены", fullListGuests.length - seated] ] as const).map(([value, label, count]) => <button aria-pressed={filter === value} className={["seat-filter-chip", filter === value ? "is-on" : ""].filter(Boolean).join(" ")} key={value} onClick={() => setFilter(value)} type="button">{label} <b>{count}</b></button>)}</div>
    <div className="seat-unseated-dialog__body">{!fullListGuests.length && !reserves.length ? <p className="seat-unseated-dialog__empty">Все рассажены.</p> : null}{fullListGuests.length && !parties.length ? <p className="seat-unseated-dialog__empty">Под фильтр и поиск никто не попал</p> : null}{parties.length ? <section aria-labelledby="seat-unseated-parties-title"><h4 id="seat-unseated-parties-title">Регистрации</h4><div className="seat-unseated-dialog__parties">{parties.map((party) => <article className="seat-unseated-party" key={party.id}><header className="seat-unseated-party__head"><div><h5>{party.name}</h5><span>{places(party.guests.length)}</span></div>{party.options.length ? <p>{party.options.join(", ")}</p> : null}{party.status || party.payment ? <p className="seat-unseated-party__meta">{[party.status, party.payment].filter(Boolean).join(" · ")}</p> : null}</header><ul className="seat-unseated-party__members">{party.guests.map((guest) => <li key={guest.key}><button className="seat-unseated-party__member" onClick={() => { if (onGuestSelect(guest.key)) requestClose(); }} type="button"><span aria-hidden="true" className="seat-unseated-party__initials">{guest.initials}</span><span><strong>{displayName(guest, party.name)}</strong><small>{guest.sourceLabel}</small></span><span className={["seat-place-pill", placementByGuestKey.has(guest.key) ? "seat-place-pill--seated" : ""].filter(Boolean).join(" ")}>{placementByGuestKey.get(guest.key) ?? "Не рассажен"}</span></button></li>)}</ul></article>)}</div></section> : null}{reserves.length ? <section aria-labelledby="seat-unseated-reserves-title" className="seat-unseated-dialog__reserves"><div className="seat-unseated-dialog__section-head"><h4 id="seat-unseated-reserves-title">Операционные резервы</h4><span>{places(reserves.length)}</span></div><ul>{reserves.map((reserve) => <li key={reserve.id}><span className="seat-unseated-party__initials">{reserve.initials}</span><span><strong>{reserve.label}</strong><small>Резерв · без регистрации</small></span></li>)}</ul></section> : null}</div>
  </div></div>, document.body);
}
function SearchIcon() { return <svg aria-hidden="true" fill="none" height="17" viewBox="0 0 17 17" width="17"><circle cx="7" cy="7" r="4.5" stroke="currentColor" strokeWidth="1.5"/><path d="m10.5 10.5 4 4" stroke="currentColor" strokeLinecap="round" strokeWidth="1.5"/></svg>; }
function group(guests: SeatingGuestPoolItem[]): Party[] { const map = new Map<string, SeatingGuestPoolItem[]>(); guests.forEach((guest) => map.set(guest.registrationId, [...(map.get(guest.registrationId) ?? []), guest])); return Array.from(map, ([id, list]) => { const ordered = [...list].sort((a, b) => a.source !== b.source ? a.source === "participant" ? -1 : 1 : (a.guestIndex ?? 0) - (b.guestIndex ?? 0)); const participant = ordered.find((guest) => guest.source === "participant"); return { id, guests: ordered, name: participant?.displayName || ordered.find((guest) => guest.participantDisplayName)?.participantDisplayName || "Регистрация", options: Array.from(new Set(ordered.flatMap((guest) => guest.optionTitles).filter(Boolean))), status: ordered.find((guest) => guest.status)?.status ? getRegistrationStatusLabel(ordered.find((guest) => guest.status)!.status!) : null, payment: ordered.find((guest) => guest.paymentStatus)?.paymentStatus ? formatPaymentStatus(ordered.find((guest) => guest.paymentStatus)!.paymentStatus!) : null }; }); }
function displayName(guest: SeatingGuestPoolItem, participant: string) { return guest.source === "participant" ? guest.displayName : guest.guestName?.trim() || `Гость ${guest.guestIndex ?? 1} · ${participant}`; }
function plural(n: number, one: string, few: string, many: string) { const a = Math.abs(n) % 100, b = a % 10; return a >= 11 && a <= 14 ? many : b === 1 ? one : b >= 2 && b <= 4 ? few : many; }
function person(n: number) { return `${n} ${plural(n, "человек", "человека", "человек")}`; } function registrations(n: number) { return `${n} ${plural(n, "регистрация", "регистрации", "регистраций")}`; } function places(n: number) { return `${n} ${plural(n, "место", "места", "мест")}`; }
